#!/bin/bash

YELLOW='\033[1;33m'
CYAN='\033[1;96m'
NC='\033[0m'
MOUNTAIN='\xE2\x9B\xB0'

JAVA_RUNTIME=`/usr/libexec/java_home -v 1.8`
DATE=`date +%Y-%m-%d`

APP_NAME="Interface"
JAR_NAME="Interface.jar"

build_native () {
    printf "${MOUNTAIN}  Building ${CYAN}${APP_NAME}${NC} app package...\n"
    javapackager -deploy \
      -native image \
      -nosign \
      -outdir out \
      -outfile interface \
      -srcfiles out/Interface.jar \
      -appclass system_main.RockAnalysis \
      -name $APP_NAME \
      -title "Geochemical Ablation Interface" \
      -Bruntime=${JAVA_RUNTIME} \
      -Bicon=resources/app/icon.icns
    printf "${MOUNTAIN}  ${CYAN}${APP_NAME}${NC} built to ${YELLOW}/out/bundles/${APP_NAME}${NC} \n"
}

if [ $# -eq 0 ]; then
  build_native
elif [ "$1" == "--release" ]; then
  if [ "$#" -eq 2 ]; then
    build_native
    RELEASE_VERSION_LABEL=${2}_$DATE
    mkdir -p release/${RELEASE_VERSION_LABEL}
    BUILD_NAME="${APP_NAME}_${RELEASE_VERSION_LABEL}"
    OSX_NAME="OSX_${BUILD_NAME}.zip"
    CROSS_PLATFORM="CrossPlatform_${BUILD_NAME}.zip"
    pushd out/bundles
    zip -r $OSX_NAME ./${APP_NAME}.app > /dev/null 2>&1
    popd
    pushd out
    zip -r $CROSS_PLATFORM ./$JAR_NAME > /dev/null 2>&1
    popd
    mv out/bundles/$OSX_NAME release/${RELEASE_VERSION_LABEL}/
    mv out/$CROSS_PLATFORM release/${RELEASE_VERSION_LABEL}/
    printf "${MOUNTAIN}  Build ${YELLOW}$BUILD_NAME${NC} release complete \n"
  else
    printf "${MOUNTAIN}  ${YELLOW}Error:${NC} specify a release version when using ${CYAN}--release${NC} \n"
  fi
else
  printf "${MOUNTAIN}  ${YELLOW}Error:${NC} ${CYAN}$1${NC} not a valid parameter (Did you mean ${CYAN}--release${NC}?)\n"
fi
